using System;
using System.Collections.Generic;

namespace prj_backend.Model
{
    public partial class AuditBond
    {
        public string? Username { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string? TransactionAction { get; set; }
        public long? BondId { get; set; }
        public string? OldSecurityDescription { get; set; }
        public string? NewSecurityDescription { get; set; }
        public string? OldSecurityName { get; set; }
        public string? NewSecurityName { get; set; }
        public string? OldAssetType { get; set; }
        public string? NewAssetType { get; set; }
        public string? OldInvestmentType { get; set; }
        public string? NewInvestmentType { get; set; }
        public double? OldTradingFactor { get; set; }
        public double? NewTradingFactor { get; set; }
        public double? OldPricingFactor { get; set; }
        public double? NewPricingFactor { get; set; }
        public string? OldIsin { get; set; }
        public string? NewIsin { get; set; }
        public string? OldBbgTicker { get; set; }
        public string? NewBbgTicker { get; set; }
        public string? OldBbgUniqueId { get; set; }
        public string? NewBbgUniqueId { get; set; }
        public string? OldCusip { get; set; }
        public string? NewCusip { get; set; }
        public string? OldSedol { get; set; }
        public string? NewSedol { get; set; }
        public DateTime? OldFirstCouponDate { get; set; }
        public DateTime? NewFirstCouponDate { get; set; }
        public string? OldCouponCap { get; set; }
        public string? NewCouponCap { get; set; }
        public string? OldCouponFloor { get; set; }
        public string? NewCouponFloor { get; set; }
        public double? OldCouponFrequency { get; set; }
        public double? NewCouponFrequency { get; set; }
        public double? OldCouponRate { get; set; }
        public double? NewCouponRate { get; set; }
        public string? OldCouponType { get; set; }
        public string? NewCouponType { get; set; }
        public string? OldSpread { get; set; }
        public string? NewSpread { get; set; }
        public bool? OldIsCallable { get; set; }
        public bool? NewIsCallable { get; set; }
        public bool? OldFixToFloat { get; set; }
        public bool? NewIsFixToFloat { get; set; }
        public bool? OldIsPutable { get; set; }
        public bool? NewIsPutable { get; set; }
        public DateTime? OldIssueDate { get; set; }
        public DateTime? NewIssueDate { get; set; }
        public DateTime? OldLastResetDate { get; set; }
        public DateTime? NewLastResetDate { get; set; }
        public DateTime? OldMaturity { get; set; }
        public DateTime? NewMaturity { get; set; }
        public double? OldMaxCallNoticeDays { get; set; }
        public double? NewMaxCallNoticeDays { get; set; }
        public DateTime? OldMaxPutNoticeDays { get; set; }
        public DateTime? NewMaxPutNoticeDays { get; set; }
        public DateTime? OldPenultimateCouponDate { get; set; }
        public DateTime? NewPenultimateCouponDate { get; set; }
        public string? OldResetFrequency { get; set; }
        public string? NewResetFrequency { get; set; }
        public bool? OldHasPosition { get; set; }
        public bool? NewHasPosition { get; set; }
        public double? OldMacaulayDuration { get; set; }
        public double? NewMacaulayDuration { get; set; }
        public double? OldVolatility30days { get; set; }
        public double? NewVolatility30days { get; set; }
        public double? OldVolatility90days { get; set; }
        public double? NewVolatility90days { get; set; }
        public double? OldConvexity { get; set; }
        public double? NewConvexity { get; set; }
        public double? OldAvgVolume30days { get; set; }
        public double? NewAvgVolume30days { get; set; }
        public string? OldPfAssetClass { get; set; }
        public string? NewPfAssetClass { get; set; }
        public string? OldPfCountry { get; set; }
        public string? NewPfCountry { get; set; }
        public string? OldPfCreditRating { get; set; }
        public string? NewPfCreditRating { get; set; }
        public string? OldPfCurrency { get; set; }
        public string? NewPfCurrency { get; set; }
        public string? OldPfInstrument { get; set; }
        public string? NewPfInstrument { get; set; }
        public string? OldPfLiquidityProfile { get; set; }
        public string? NewPfLiquidityProfile { get; set; }
        public string? OldPfMaturity { get; set; }
        public string? NewPfMaturity { get; set; }
        public string? OldPfNaicsCode { get; set; }
        public string? NewPfNaicsCode { get; set; }
        public string? OldPfRegion { get; set; }
        public string? NewPfRegion { get; set; }
        public string? OldPfSector { get; set; }
        public string? NewPfSector { get; set; }
        public string? OldPfSubAssetClass { get; set; }
        public string? NewPfSubAssetClass { get; set; }
        public string? OldBbgIndustryGroup { get; set; }
        public string? NewBbgIndustryGroup { get; set; }
        public string? OldBbgIndustrySubGroup { get; set; }
        public string? NewBbgIndustrySubGroup { get; set; }
        public string? OldBbgIndustrySector { get; set; }
        public string? NewBbgIndustrySector { get; set; }
        public string? OldIssueCountry { get; set; }
        public string? NewIssueCountry { get; set; }
        public string? OldIssueCurrency { get; set; }
        public string? NewIssueCurrency { get; set; }
        public string? OldIssuer { get; set; }
        public string? NewIssuer { get; set; }
        public string? OldRiskCurrency { get; set; }
        public string? NewRiskCurrency { get; set; }
        public DateTime? OldPutDate { get; set; }
        public DateTime? NewPutDate { get; set; }
        public double? OldPutPrice { get; set; }
        public double? NewPutPrice { get; set; }
        public double? OldAskPrice { get; set; }
        public double? NewAskPrice { get; set; }
        public double? OldHighPrice { get; set; }
        public double? NewHighPrice { get; set; }
        public double? OldLowPrice { get; set; }
        public double? NewLowPrice { get; set; }
        public double? OldOpenPrice { get; set; }
        public double? NewOpenPrice { get; set; }
        public double? OldVolume { get; set; }
        public double? NewVolume { get; set; }
        public double? OldBidPrice { get; set; }
        public double? NewBidPrice { get; set; }
        public double? OldLastPrice { get; set; }
        public double? NewLastPrice { get; set; }
        public DateTime? OldCallDate { get; set; }
        public DateTime? NewCallDate { get; set; }
        public double? OldCallPrice { get; set; }
        public double? NewCallPrice { get; set; }
    }
}
